name = "boozeaccounting"
compatibility_date = "2024-09-01"
main = "src/worker.ts"

kv_namespaces = [
  { binding = "APP_KV", id = "9bf24f0a7e274730993b0ef58a09c2e1" }
]

[vars]
ENV = "production"

[assets]
directory = "./dist"
